### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by GMLudo** [aio-libs/aiohttp_jinja2#1]
Hi,

I'm sorry to spam you today, but could you publish aiohttp_jinja2 on PyPI ?
I'm using it, it will simpler to install instead of via Git repository.

BTW, it works like a charm.

Regards.

**Comment by kxepal** [comment]
+1

**Comment by asvetlov** [comment]
I still not convicted the API is stable.

I can make **unstable** 0.0.1 release though.

**Comment by kxepal** [comment]
*unstable* or *beta* is ok for me.

**Comment by GMLudo** [comment]
No problems for me if you change the API for the next version: it's the open source game, especially with a 0.x.y release.

**Comment by asvetlov** [comment]
Done

**Comment by GMLudo** [comment]
Thank you @asvetlov, but I've an issue with archive on PyPI, it seems that CHANGES.txt is missing:

<pre>
(pyvenv) lg@steroids:~/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour$ pip install aiohttp_jinja2
Downloading/unpacking aiohttp-jinja2
  Downloading aiohttp_jinja2-0.0.1.tar.gz
  Running setup.py (path:/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py) egg_info for package aiohttp-jinja2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 26, in <module>
        lond_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
      File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 16, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/CHANGES.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 26, in <module>

    lond_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),

  File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 16, in read

    return open(os.path.join(os.path.dirname(__file__), f)).read().strip()

FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/CHANGES.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2
Storing debug log for failure in /home/lg/.pip/pip.log</pre>

**Comment by asvetlov** [comment]
Try again please

On Thu, Jan 8, 2015 at 5:56 PM, Ludovic Gasc <notifications@github.com>
wrote:

> Thank you @asvetlov <https://github.com/asvetlov>, but I've an issue with
> archive on PyPI, it seems that CHANGES.txt is missing:
>
> (pyvenv) lg@steroids:~/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour$ pip install aiohttp_jinja2
> Downloading/unpacking aiohttp-jinja2
>   Downloading aiohttp_jinja2-0.0.1.tar.gz
>   Running setup.py (path:/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py) egg_info for package aiohttp-jinja2
>     Traceback (most recent call last):
>       File "", line 17, in
>       File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 26, in
>         lond_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
>       File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 16, in read
>         return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
>     FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/CHANGES.txt'
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>
>   File "", line 17, in
>
>   File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 26, in
>
>     lond_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
>
>   File "/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/setup.py", line 16, in read
>
>     return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
>
> FileNotFoundError: [Errno 2] No such file or directory: '/home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2/CHANGES.txt'
>
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /home/lg/Documents/IDEA/FrameworkBenchmarks/frameworks/Python/API-Hour/pyvenv/build/aiohttp-jinja2
> Storing debug log for failure in /home/lg/.pip/pip.log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiohttp_jinja2/issues/1#issuecomment-69199574>
> .
>



-- 
Thanks,
Andrew Svetlov

**Comment by GMLudo** [comment]
Ok, it works, thank you.

**Comment by filmackay** [comment]
I get this same error on 0.3.0 PyPI now..

**Comment by jettify** [comment]
Version 0.3.0 installs without any issues using PIP on my machine. Could you show complete traceback?
