### ISSUE TITLE
Pass request object and router.url method to templates 

### ISSUE THREAD

**Issue by gleb-chipiga** [aio-libs/aiohttp_jinja2#13]
Need the ability to access the request object and router.url method from the template

**Comment by asvetlov** [comment]
You may pass `request` into jinja context explicitly, isn't it?

**Comment by gleb-chipiga** [comment]
Of course, but many web frameworks pass a set of useful objects and functions into template namespace. 
They have this feature of the box.

**Comment by asvetlov** [comment]
Good to them, but I don't want to introduce jinja2 middleware for implicitly passing request into context.
What frameworks are you talking about? 
AFAIK only Flask support implicit request in template context due global nature of request object in Flask (I consider global-ness is a bad thing). Maybe there is possibility to do the same with bottle, but for Django or Pyramid it's just impossible.

**Comment by gleb-chipiga** [comment]
I'm not just talking about the request. Django has django.core.context_processors.request and  for example 'url' tag to resolve url names. Tornado has 'reverse_url' and 'static_url' template functions and 'request' and 'handler' objects.

**Comment by asvetlov** [comment]
Ok, I'm going to change my mind.
I've closed #8 as wontfix but after second request for the same feature I thing it worth to be implemented.

If you or @imbolc want to pickup PR #8  I will merge it after kindly review.
For now I see at least two issues:
1. There are no tests for implementation
2. Keys for application and request should be prefixed with `'aiohttp_jinja2_'` to avoid clashing with other libraries.

**Comment by imbolc** [comment]
Hey :) I am quite busy right now, but in one-two weeks I would have time to do it. Thanks :)

**Comment by asvetlov** [comment]
Cool!

On Tue, Jun 9, 2015 at 5:54 AM, Imblc <notifications@github.com> wrote:

> Hey :) I am quite busy right now, but in one-two weeks I would have time
> to do it. Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiohttp_jinja2/issues/13#issuecomment-110203672>
> .
>



-- 
Thanks,
Andrew Svetlov

**Comment by imbolc** [comment]
Done :)

**Comment by asvetlov** [comment]
Fixed in #14
