### ISSUE TITLE
The order of arguments differs from django.render

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp_jinja2#22]
I think it's good idea always pass request as first argument. Because it's first argument in django views, messages, render e.t.c.

**Comment by asvetlov** [comment]
The ship has sailed more than a year ago.

**Comment by imbolc** [comment]
But version number still allows you to change api.

**Comment by asvetlov** [comment]
I don't want to break backward compatibility just to follow Django's convention.

**Comment by imbolc** [comment]
It's not necessary with `render_template`, you can just add django-style alias like:
```
def render(request, template, context, **kw):
    return render_template(template, request, **kw)
```
But I'm not sure what to do with `render_string`
