### ISSUE TITLE
No way to set HTTP status in render_template

### ISSUE THREAD

**Issue by peter-conalgo** [aio-libs/aiohttp_jinja2#24]
It does not seem possible to render a 404 (or any non-200) response using `render_template()` because it does not have a means to pass arguments to the constructor of `web.Response`. The status of the response object cannot be changed after it's initialized, so we need to pass in `status=404`.

Related issue: not all my templates will be HTML, so `content_type` should probably be an optional argument as well.

For best forwards-compatibility, you may want to send all unknown keyword arguments into `web.Response`.

**Comment by trivigy** [comment]
Hey,

Looking at the code there is a way for you to change the status after creation and more.

```python
async def handler(request):
    response = render_template(...)
    response.set_response(404, None)   <-- StreamResponse::set_response(status, reason)
    response.content_type = 'application/json'
    return response
```

**Comment by popravich** [comment]
`set_status`, actually -- [aiohttp.web.StreamResponse.set_status](http://aiohttp.readthedocs.io/en/stable/web_reference.html?highlight=set_status#aiohttp.web.StreamResponse.set_status)

**Comment by peter-conalgo** [comment]
Yes, quite right. Sorry I missed that.
