### ISSUE TITLE
How do I access local files from generated html?

### ISSUE THREAD

**Issue by cclauss** [aio-libs/aiohttp_jinja2#26]
I would like to access images, etc from `.` or `./static`.  See https://github.com/cclauss/where_is_lenna/

**Comment by asvetlov** [comment]
You should either handle static files by reverse proxy (nginx for example) or call `.add_static()` like https://github.com/KeepSafe/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/routes.py#L9

The second approach is not recommended for production usage.

**Comment by cclauss** [comment]
Magic!  Thanks much!
