### ISSUE TITLE
How to pass parameters by url in template?

### ISSUE THREAD

**Issue by 631068264** [aio-libs/aiohttp_jinja2#29]
`route= '/b/{a}'  name='b' `   

The code in html
`<a href='{{url("b",a=3)}}'>GO to b</a>`
I want to get the path is `/b/3`
TypeError: url() got an unexpected keyword argument 'a'

And I want to know if want to get the path like `/b?a=3&c=4` how to do this ?

**Comment by 631068264** [comment]
OK I find it in [aiohttp about reverse url ](http://aiohttp.readthedocs.io/en/stable/web.html#reverse-url-constructing-using-named-resources)

**Comment by barrachri** [comment]
Happy to re-open this issue:

url = self.request.app.router['set_new_password'].url_for(token=token)

it works fine.

{{ url('set_new_password', token=token) }}

TypeError: url() got an unexpected keyword argument 'token'

https://github.com/aio-libs/aiohttp-jinja2/blob/master/aiohttp_jinja2/__init__.py#L30

url should be deprecated for url_for ?
