### ISSUE TITLE
web.View templating error

### ISSUE THREAD

**Issue by stenvix** [aio-libs/aiohttp_jinja2#30]
Get 
```
TypeError: get() missing 1 required positional argument: 'request'
```
when class function have next signature
```
class IndexView(View):
    @aiohttp_jinja2.template('index.html')
    async def get(self, request):
        return {'name': 'Andrew', 'surname': 'Svetlov'}
```

**Comment by stenvix** [comment]
My mistake, but why its crashed when method get more then two parameters?

**Comment by asvetlov** [comment]
There is no magic.
*Web handler* should have the only `request` parameter.
*Class-based view* has exactly two parameters: `self` and `request`.
Additional parameters are not allowed.

**Comment by stenvix** [comment]
@asvetlov as I paste code my web.View "get" method have two parameters, but i had TypeError, 
```
 async def get(self, request):
        return {'name': 'Andrew', 'surname': 'Svetlov'}
```
correct method need to have just one self parameter?
```
 async def get(self):
        return {'name': 'Andrew', 'surname': 'Svetlov'}
```

**Comment by asvetlov** [comment]
Please take a look on the following test: https://github.com/aio-libs/aiohttp_jinja2/blob/master/tests/test_simple_renderer.py#L88-L106

Yes, class based views accepts only `self` and retrieves `request` as `self.request`.

Sorry for misleading in previous answer.
